export const getData = () => [
  {
    id: 1,
    title: 'Babel',
    body: 'Babel merupakan tools open-source yang digunakan untuk mengubah sintaks ECMAScript 2015+ menjadi sintaks yang didukung oleh JavaScript engine versi lama. Babel sering dipakai ketika kita menggunakan sintaks terbaru termasuk sintaks JSX.',
    archived: true,
    createdAt: '2022-04-14T04:27:34.572Z',
  },
  {
    id: 2,
    title: 'Webpack',
    body: 'Webpack adalah bundler modul untuk aplikasi JavaScript modern. Webpack memudahkan pengembang dalam mengelola dependensi serta mengoptimalkan performa dengan cara menggabungkan modul-modul menjadi satu file.',
    archived: false,
    createdAt: '2022-05-20T11:15:12.345Z',
  },
  {
    id: 3,
    title: 'React',
    body: 'React adalah library JavaScript untuk membangun antarmuka pengguna. React menggunakan pendekatan deklaratif untuk merender UI berdasarkan data yang berubah, membuatnya sangat efisien dan mudah dikelola.',
    archived: true,
    createdAt: '2022-06-10T08:42:19.123Z',
  },
  {
    id: 4,
    title: 'Node.js',
    body: 'Node.js adalah runtime JavaScript yang dibangun di atas mesin V8 Google Chrome, memungkinkan eksekusi JavaScript di server-side. Ini populer digunakan untuk membangun aplikasi web back-end yang skalabel dan cepat.',
    archived: true,
    createdAt: '2022-07-05T14:27:10.999Z',
  },
  {
    id: 5,
    title: 'Express.js',
    body: 'Express.js adalah framework web yang minimalis dan fleksibel untuk Node.js, memberikan fitur-fitur yang kuat untuk membangun aplikasi web dan API, seperti routing dan middleware.',
    archived: false,
    createdAt: '2022-08-22T17:03:55.678Z',
  },
  {
    id: 6,
    title: 'TypeScript',
    body: 'TypeScript adalah bahasa pemrograman yang dikembangkan oleh Microsoft. TypeScript adalah superset dari JavaScript yang menambahkan fitur-fitur seperti tipe statis dan alat pengembangan yang lebih baik.',
    archived: true,
    createdAt: '2022-09-15T09:58:01.456Z',
  },
  {
    id: 7,
    title: 'Vue.js',
    body: 'Vue.js adalah framework JavaScript progresif yang digunakan untuk membangun antarmuka pengguna. Ini dirancang agar dapat diadopsi secara bertahap dan memiliki ekosistem yang mendukung pengembangan aplikasi single-page.',
    archived: false,
    createdAt: '2022-10-01T12:00:00.000Z',
  },
  {
    id: 8,
    title: 'MongoDB',
    body: 'MongoDB adalah database NoSQL berbasis dokumen yang menyimpan data dalam bentuk JSON-like. MongoDB digunakan untuk menyimpan data yang tidak memiliki skema tetap dan dapat berkembang seiring waktu.',
    archived: true,
    createdAt: '2022-10-10T14:30:45.567Z',
  },
  {
    id: 9,
    title: 'GraphQL',
    body: 'GraphQL adalah bahasa kueri untuk API yang memberikan klien kemampuan untuk meminta data secara spesifik. Ini menawarkan fleksibilitas lebih besar dibandingkan REST dan memungkinkan pengurangan data over-fetching.',
    archived: false,
    createdAt: '2022-11-01T09:20:12.345Z',
  },
  {
    id: 10,
    title: 'Docker',
    body: 'Docker adalah platform yang memungkinkan pengembang untuk mengemas aplikasi mereka ke dalam container yang terisolasi, yang dapat dijalankan secara konsisten di berbagai lingkungan.',
    archived: true,
    createdAt: '2022-11-15T16:45:30.123Z',
  },
  {
    id: 11,
    title: 'Kubernetes',
    body: 'Kubernetes adalah platform orkestrasi container open-source yang digunakan untuk mengotomatisasi penyebaran, scaling, dan pengelolaan aplikasi yang dikontainerisasi.',
    archived: false,
    createdAt: '2022-12-01T11:10:55.789Z',
  },
];
